# Codecov configuration to make it a bit less noisy
coverage:
  status:
    patch: false
    project:
      default:
        threshold: 50%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
ignore:
  - "ensemble_md.utils.py"
  - "ensemble_md.ensemble_md.py"
  - "ensemble_md.run_ensemble_EXE.py"
