# Simulation parameters
gmx_executable: 'gmx'               
gro: sys.gro
top: sys.top
mdp: expanded.mdp             
n_sim: 4
n_iter: 5         
s: 1                         
nst_sim: 500
runtime_args: {'-nt': '1'}

# Data analysis parameters
free_energy: True
