name: docs
channels:
build:
  apt_packages:
    - libclang
    - cmake
    - mpich
    - libmpich-dev
dependencies:
  - python
  - pandoc
  - ipykernel
  - pip
 
  # Pip-only installs
  - pip:
    - sphinx  # 4.2.0
    - nbsphinx
    - sphinx_rtd_theme
    - docutils==0.17.1
    - pyyaml
    - numpy
    - natsort
    - argparse
    - alchemlyb==2.0.0
    - seaborn
    - matplotlib
    - pyemma
    - pymbar==4.0.1
    - mpi4py
    - gmxapi==0.4.0
