name: docs
channels:
dependencies:
  - python
  - pandoc
  - ipykernel
  - pip
  
  # Pip-only installs
  - pip:
    - sphinx
    - nbsphinx
    - sphinx_rtd_theme
    - docutils==0.17.1
    - pyyaml
    - numpy
    - natsort
    - argparse
    - alchemlyb
    - seaborn
    - matplotlib
    # - mpi4py
