name: docs
channels:
dependencies:
  - python
  - pandoc
  - ipykernel
  - pip
  
  # Pip-only installs
  - pip:
    - sphinx==4.2.0
    - nbsphinx==0.8.9
    - sphinx_rtd_theme==1.0.0
    - docutils==0.17.1
